legacy 파일 삭제
tastetionary/tastetionary-client pull request #166
Opened 2024-12-01 12:54 UTC by yejiiha

## 📑 제목
legacy 파일 삭제

## 📎 관련 이슈
resolve #(이슈 번호)
  
## 💬 작업 내용
- 미사용 파일 삭제: src/example, app/example
- 패키지 교체: @homekeeper89/taste_dict => @taehoya/tastetionary
 
## 🚧 PR 특이 사항
- 없습니다

## 🕰 실제 소요 시간
0.5h

2024-12-01 15:07 UTC, Taehoya requested changes

2024-12-01 15:07 UTC, Taehoya commented on .github/workflows/build.yml
>            echo "" >> $HOME/.npmrc
여기까지 지워주세요!

2024-12-01 15:07 UTC, Taehoya commented on .github/workflows/build_and_push.yml
>            echo "" >> $HOME/.npmrc
위 코멘트 참고 부탁드립니다

2024-12-02 05:58 UTC, yejiiha commented on .github/workflows/build.yml
>            echo "" >> $HOME/.npmrc
네 다시 수정해서 커밋했습니다! 그런데 제가 새로 수정한 부분이 말씀하신 부분이 맞는지 모르겠어요

2024-12-02 11:56 UTC, hovelopin approved these changes
확인했습니다. 고생하셨습니다. 😄

2024-12-02 12:56 UTC, Taehoya approved these changes

2024-12-02 12:58 UTC, merged